name: Pytest

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
    paths:
      - '**/*.py'
      - '.github/workflows/pytest.yaml'
      - 'requirements.txt'
  pull_request:
    branches:
      - develop
      - main
    paths:
      - '**/*.py'
      - '.github/workflows/pytest.yaml'
      - 'requirements.txt'
  schedule:
    # Scheduled workflows will only run on the default branch (main)
    - cron: '30 0 1 1/2 *' # every 2 months on the first day at 00:30

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

# When calling a reusable workflow that needs elevated permissions, these permissions
# must be explicitly specified in the calling workflow.
permissions:
  # required for all workflows
  security-events: write
  # only required for workflows in private repositories
  actions: read
  contents: read

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    uses: KostasStefanidis/github-workflows/.github/workflows/pytest.yaml@main
    with:
      python_version: ${{ matrix.python-version }}
