name: Pylint

on:
  push:
    branches: [  main ]
    paths:
      - '**.py'
      - '.github/workflows/pytest.yaml'
      - 'requirements.txt'
  pull_request:
    branches: [  main ]
    paths:
      - '**.py'
      - '.github/workflows/pytest.yaml'
      - 'requirements.txt'
  workflow_dispatch:

# When calling a reusable workflow that needs elevated permissions, these permissions
# must be explicitly specified in the calling workflow.
permissions:
  # required for all workflows
  security-events: write
  # only required for workflows in private repositories
  actions: read
  contents: read

jobs:
  pytest:    
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    
    uses: KostasStefanidis/github-workflows/.github/workflows/pytest.yaml@main
    with:
      python_version: ${{ matrix.python-version }}
